### ISSUE TITLE
Ambiguity in 6.5.2 b

### ISSUE THREAD

**Issue by DorusKeijzer** [jkorb/KI1V13001-Inleiding-Logica#104]
Another possible problem that should be pushed for next year: 

When discussing this exercise in the work groups, we were confused why 6.5.2b was incorrect:

![image](https://user-images.githubusercontent.com/83274869/136075390-b6bef7dd-042a-49ab-86a2-3358f5953fac.png)
 
We initially parsed this statement as "For all formulas phi in gamma and for all valuations v, ...", thinking that the "for each" phrase at the beginning of the sentence distributes to both the "phis in gamma" and the "valuation v" part of the phrase: "for each formula, ..., and for each valuation", so we concluded that this must mean that gamma is unsatisfiable. When we found out that our answer to this question was wrong, we took another look and found we were supposed to parse it as if "for each" didn't distribute to the valuation: "for each formula,... and _the one_ valuation ... ", which would not necessarily make gamma unsatisfiable. 

Part of the confusion is that a few lines earlier, we're confronted with 6.5.1 f, where "for all" _does_ indeed distribute to both the formulas and the valuations. 

![image](https://user-images.githubusercontent.com/83274869/136076254-5536dbfe-5623-47d1-ba47-c98575a568af.png)

(here, f is correct according to the answers)

With this one it is obvious that it does distribute, because it uses "for all" and "valuations" (plural) rather than "valuation", though it does set a precedent that terms such as "for all" can distribute. 6.5.2b on the other hand, uses "for each", which means we cannot look at whether the nouns are plural to determine whether the term distributes because "for each" always requires the nouns it refers to to be singular.

**Comment by DorusKeijzer** [comment]
right! I hadn't considered that at all. I will report this to the person who asked the question. 

I think a hint might indeed be in place here, or instead, this explanation could be provided in appendix F.

**Comment by jkorb** [comment]
Great! I'll add an explanation/hint in the solution :)
