### ISSUE TITLE
GRAVE mistake on page 277 that needs immediate rectification

### ISSUE THREAD

**Issue by paggaman** [jkorb/KI1V13001-Inleiding-Logica#64]
"... But it’s a bit like with scorpions: the smaller the more poisonous ..."

Not only does this make the mistake of conflating the words "poisonous" and "venomous" (scorpions are venomous as a venomous animal is one that releases poison when _it bites or sting another animal_ and a poisonous animals is one that releases poison when _another animal bites it_), it also promotes a common mistunderstanding that has no basis in reality and perpetuates a stereotype  and is harmful to smaller scorpions worldwide. 

According to emperical research, there seems to be no correlation between scorpion size and the potency of their venom, nor is there one for scorpion age (though interestingly, the size of the pinchers does give an indication).  The smaller scorpion community has had to endure prejudice ever since this myth got widespread attention, primarly as a result of a throwaway line in the the 2008 movie "Indiana Jones and the Kingdom of the Crystal Skull", and as a representative of the small scorpion community, it pains me to see this stereotype carelessly perpetuated in the instruction manual of a course that in all other regards meets the professionality an academic course should aspire to. Please rectify this mistake by using another simile that _does_ reference a size based correlation that is empirically supported (for instance: "But it’s a bit like with strawberries: the smaller the sweeter"). 

I thank you on behalf of the community I represent.

**Comment by jkorb** [comment]
Sorry for the late reply. And for the insensitive remarks. I'll fix this for this years version (pushing the change later today).
