### ISSUE TITLE
Possibly confusing sentence in 3.6.9

### ISSUE THREAD

**Issue by 607GitHub** [jkorb/KI1V13001-Inleiding-Logica#66]
Okay, it's possible that this is just me, but since first reading the lecture notes I had never been able to make sense of the following sentence in 3.6.9: "The convention hereby is that the first input is in the first column and the second input in the first row." Now that I'm studying the sentence once more, I finally get it, and it is correct.
I think what confused me is that 'first' is used in two different ways in the sentence, and that I started counting within the line boundaries.
Maybe it would be clearer if it said "left-most column" and "top row" instead?
Have a look; it's possible that it's just me. :)

**Comment by jkorb** [comment]
Very good suggestion!
