### ISSUE TITLE
Potentially confusing clarification in 8.2.12

### ISSUE THREAD

**Issue by 607GitHub** [jkorb/KI1V13001-Inleiding-Logica#68]
8.2.12 is charming, but the clarification at the end is stronger than needed. I asked my students to give the weaker sufficient statement in class, and they got it, but because people are just getting started with quantifiers here, it could confuse some. I do quite like the sentiment, so maybe you could add as a footnote that you believing in one of the students would be enough for the latter formula to be untrue.
On a related note, one might wonder why, if you believe in every single student, you would still be surprised if every student passes. But with the proposed footnote, I think this passage would be unlikely to mislead while still adding some welcome charm to the course notes.

**Comment by jkorb** [comment]
Thanks @607GitHub ! Well, it's a bit like the so-called Lottery Paradox (https://en.wikipedia.org/wiki/Lottery_paradox). But I'll add the footnote.
