### ISSUE TITLE
Confusing definition because of ambiguous use of = (8.5.3)

### ISSUE THREAD

**Issue by 607GitHub** [jkorb/KI1V13001-Inleiding-Logica#69]
The definition given in 8.5.3 is very hard to read. In my experience, (i)(b) is most problematic, because the symbol = is used in three different ways (the same is true for (ii)(b), but there the last use is clearly disconnected). Unfortunately I don't have any ideas for improvements, but maybe you can look into it.

**Comment by jkorb** [comment]
Good point, I'll clarify
