### ISSUE TITLE
Various typos/grammatical errors in syllabus

### ISSUE THREAD

**Issue by Fakerick1** [jkorb/KI1V13001-Inleiding-Logica#83]
https://github.com/jkorb/KI1V13001-Inleiding-Logica/blob/main/lib/syllabus/md/02_communication.md
Zoals goedgekeurd door je werkgroepleider kunt je hier ook je huiswerkopdrachten indienen
kunt > kun

https://github.com/jkorb/KI1V13001-Inleiding-Logica/blob/main/lib/syllabus/md/04_format.md
Als er reden zijn
reden > redenen

https://github.com/jkorb/KI1V13001-Inleiding-Logica/blob/main/lib/syllabus/md/06_collaboration.md
Als je nog GitHub en git nog niets zegt > Als GitHub en git je nog niets zeggen

https://github.com/jkorb/KI1V13001-Inleiding-Logica/blob/main/lib/syllabus/md/07_oefeningen.md
Dit is jij *actieve deelname* > Dit is jouw *actieve deelname*

https://github.com/jkorb/KI1V13001-Inleiding-Logica/blob/main/lib/syllabus/md/08_cijfers.md
met jij delen > met jou delen

Als je mij toegang tot de repo geeft kan ik de changes zelf committen via een PR.

**Comment by jkorb** [comment]
Thanks @Fakerick1 ! First issue of this year's course :)

**Comment by jkorb** [comment]
Oh, en je kunt gewoon: fork > edit > PR doen. Je hebt geen toegang nodig :) Maar voor nu heb ik de typos even zelf gefixed.
