### ISSUE TITLE
mogelijk incorrecte voetnoot pagina 58

### ISSUE THREAD

**Issue by MotevanReij** [jkorb/KI1V13001-Inleiding-Logica#95]
De volgende tekst staat in de voetnoot.

Note that the definitions of even and odd can easily be generalized to Z: a number
n ∈ Z is even iff there exists a k ∈ Z such that 2k = 2n. And a number n ∈ Z is odd iff n
is not even.

Volgens mij had hier moeten staan.

Note that the definitions of even and odd can easily be generalized to Z: a number
n ∈ Z is even iff there exists a k ∈ Z such that **2k = n.** And a number n ∈ Z is odd iff n
is not even.

**Comment by jkorb** [comment]
Je hebt helemaal gelijk @MotevanReij ! Ik ga het zo fixen q
